version: '3.8'

services:
  app:
    build: ./app
    container_name: application
    ports:
      - "80:80"
    depends_on:
      - Mariadb
    restart: always

  Mariadb:
    build: 
      context: .  
      dockerfile: Dockerfile-mariadb
    container_name: Mariadb
    restart: always
    volumes: 
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sentrifugo_db
      MYSQL_USER: sentrifugo_user
      MYSQL_PASSWORD: sentrifugo_pass
    ports:
      - "3306:3306"
