services:
  app:
    build: ./app
    container_name: sentrifugo
    ports:
      - "80:80"
    depends_on:
      - data
    restart: always

  data:
    build: ./data
    container_name: mariadb
    restart: always
    volumes: 
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sentrifugo_db
      MYSQL_USER: sentrifugo_user
      MYSQL_PASSWORD: sentrifugo_pass
    ports:
      - "3306:3306"
volumes:
  mariadb_data:
