services:
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile_sentrifugo # Ensure this is the name of the Dockerfile in the ./app directory
    container_name: sentrifugo
    ports:
      - "80:80"
    depends_on:
      - mariadb
    restart: always

  data:
    build: 
      context: ./data
      dockerfile: Dockerfile_mariadb  # Ensure this is the name of the Dockerfile in the ./data directory
    container_name: mariadb
    restart: always
    volumes: 
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sentrifugo_db
      MYSQL_USER: sentrifugo_user
      MYSQL_PASSWORD: sentrifugo_pass
    ports:
      - "3306:3306"
