version: '3.7'

services:
  app:
    build: ./app
    container_name: application
    ports:
      - 80:80
    depends_on:
      - db
    restart: always



  db:
    build: ./db
    container_name: database
    restart: always
    volumes: 
      - ./db/data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password
      ports:
      - "3306:3306"
